FactoryGirl.define do
  factory :employee do
    business nil
last_name "MyString"
first_name "MyString"
middle_initial "MyString"
job_title "MyString"
department "MyString"
subcontractor_name "MyString"
employee_number 1
ssn "MyString"
hourly_rate "9.99"
gross_salary "9.99"
taxes "9.99"
net_salary "9.99"
start_date "2016-02-09"
end_date "2016-02-09"
end_reason_notes "MyText"
end_reason_type_code 1
end_reason_item_code 1
contact_notes "MyText"
email_address1 "MyString"
email_address2 "MyString"
email_address3 "MyString"
phone_number1 "MyString"
phone_number2 "MyString"
phone_number3 "MyString"
phone_ext1 "MyString"
phone_ext2 "MyString"
phone_ext3 "MyString"
phone_type_code1 1
phone_type_code2 1
phone_type_code3 1
phone_item_code1 1
phone_item_code2 1
phone_item_code3 1
email_type_code1 1
email_type_code2 1
email_type_code3 1
email_item_code1 1
email_item_code2 1
email_item_code3 1
status_type_code 1
status_item_code 1
created_by 1
modified_by 1
  end

end
